// PrimeVue/src/components/FieldLabel.vue
<template>
	<label
		class="text-sm font-semibold text-gray-700"
		:class="cls"
		v-if="!!text"
	>{{ text }}{{ separator }}</label>
</template>

<script setup lang="ts">
import { computed } from "vue";

export interface IFieldLabel {
	text: string;
	position?: "top" | "left";
	separator?: string;
}

const props = withDefaults(defineProps<IFieldLabel>(), {
	position: "left",
	separator: ":",
});
const cls = computed(() => {
	return {
		"mr-2 leading-8": props.position === "left",
		"mb-1": props.position === "top",
	};
});
</script>

// packages/satisfactory/src/components/FieldLabel.tsx
﻿import { ComponentProps } from "react";

export interface IFieldLabel extends ComponentProps<"label"> {
	text?: string;
	separator?: string;
}

export function FieldLabel({ text, separator = ":" }: IFieldLabel) {
	if (!text) {
		return;
	}
	return (
		<label className="mr-2 font-semibold text-gray-700 uppercase text-sm">
			{text}
			{separator}
		</label>
	);
}
