// Modeling/src/FieldLabel.vue
<template>
	<label class="text-gray-500 uppercase text-xs font-semibold flex">
		<span>{{ text }}</span>
		<span
			class="text-red-600 text-xs lowercase"
			v-if="required"
		>&nbsp;*</span>
	</label>
</template>

<script setup lang="ts">
interface IProps {
	text: string;
	required?: boolean;
}

defineProps<IProps>();
</script>

// packages/satisfactory/src/components/FieldLabel.tsx
﻿import { ComponentProps } from "react";

export interface IFieldLabel extends ComponentProps<"label"> {
	text?: string;
	separator?: string;
}

export function FieldLabel({ text, separator = ":" }: IFieldLabel) {
	if (!text) {
		return;
	}
	return (
		<label className="mr-2 font-semibold text-gray-700 uppercase text-sm">
			{text}
			{separator}
		</label>
	);
}
